### ISSUE TITLE
Support for multiple envoy instances per node

### ISSUE THREAD

**Issue by r0bj** [projectcontour/contour-operator#381]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

It would be useful to be able to deploy multiple envoy instances per k8s node.
Use case:
I use dedicated pool of nodes for envoy pods. To better utilize node resources I could run multiple envoy pods (sure, one option would be to downsize nodes but sometime it's impossible/impractical - bare metal). This approach has some positive aspect: decrease load of envoy primary thread (with the same amount of traffic going through envoy cluster). In other words it can be positive for ingress controller scalability.

What do you think?

**Comment by danehans** [comment]
@r0bj thanks for creating the issue. You can run multiple Envoy pods per node. Since a `Contour` represents an atomic unit of Contour, Envoy, etc., you need to create multiple `Contour's`. Due to https://github.com/projectcontour/contour-operator/issues/18, the operator does not support running multiple instances of Contour in the same namespace. Therefore, the `contour.spec.namespace.name` values must differ. By [default](https://github.com/projectcontour/contour-operator/blob/release-1.16/api/v1alpha1/contour_types.go#L230), Envoy pods will use port 8080 for the HTTP listener and 8443 for the HTTPS listener. These fields will need to be updated so the scheduler can schedule the two different Envoy pods on the same node. Let me know if you have cycles to help document this use case in https://projectcontour.io/
