### ISSUE TITLE
Configurable Contour and Envoy Network Endpoint Publishing

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#70]
**Please describe the problem you have**
Make Contour and Envoy network endpoints configurable. For example, I may not want to use a LB service to expose Envoy (default). I may want to only use a ClusterIP or a range of other possibilities for Contour and Envoy.

/cc @jpeach @Miciah

**Comment by danehans** [comment]
xref: https://kubernetes.slack.com/archives/C8XRH2R4J/p1603393745340600

**Comment by Miciah** [comment]
Right now, the examples on projectcontour/contour use host ports.  Host ports are not well documented.  Using host networking (which is better documented) solves the same problem for bare metal, and using node ports is preferable on cloud platforms (and on bare metal when an external load-balancer is used).  

I believe we should change the projectcontour/contour examples (a) to use host networking instead of host ports to satisfy the bare-metal use-case and (b) define a LoadBalancer-type service (which doesn't necessarily need host ports or host networking, but should be compatible with either) to satisfy the cloud use-case.  We should propose this as a change to the projectcontour/contour examples first, and then update projectcontour/contour-operator once we have made the change in projectcontour/contour.  

We'd need to verify that changing host ports to host networking does not break kind.  We'd also need to sort out any implications for SCCs (there may not be an issue for vanilla Kubernetes).  

As a follow-up, we can change contour-operator (a) to turn host networking on and omit the LB service on bare-metal platforms and (b) to turn host networking off and create the LB service on cloud platforms.

**Comment by danehans** [comment]
xref https://github.com/projectcontour/contour-operator/issues/105 to make ports configurable. containerPorts should be configurable. `nodePort` of the envoy service should be configurable when using a NodePort service.
