### ISSUE TITLE
Decision: Versioning schema for API and software/image releases

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour-operator#82]
As part of this project, we need to agree on the versioning schema both for the API objects and the software.

I propose initially:
- API versioning uses the Kubernetes versioning standards. This doesn't seem controversial, but writing it down here seems like a net win.
- Software versioning uses semver? Seems like that would make the most sense, given that's what mainline Contour does. A question I would have for everyone in this case is - do we have the operator version match the Contour version? I can see pros and cons there, but I don't want to prejudice the discussion too much.

**Comment by danehans** [comment]
xref: https://github.com/projectcontour/contour-operator/issues/55

**Comment by danehans** [comment]
Document how the operator handles upgrades/downgrades.

xref: https://github.com/projectcontour/contour-operator/issues/84

**Comment by danehans** [comment]
> do we have the operator version match the Contour version?

I would like to get input from contour maintainers (@stevesloka @jpeach @skriss) on this question.

**Comment by danehans** [comment]
+1 for having the operator's version match contour's version. I think having the versions match will be easier on users to understand and for developers to support.

**Comment by jpeach** [comment]
> +1 for having the operator's version match contour's version. I think having the versions match will be easier on users to understand and for developers to support.

That sounds OK to me and is consistent with @youngnick's initial proposal.

**Comment by youngnick** [comment]
Yes, I'm +1 on the versions matching, given the model of "this version of the operator will install a particular version of Contour".

**Comment by skriss** [comment]
Yep, likewise.

**Comment by stevesloka** [comment]
- How do users downgrade if they upgrade and run into problems?
  - Deploy an older version?
- Does the operator upgrade config file / flags and then remove when upgrading?
  - Do we need to move to a CRD for config rather than configmap? 
- Do folks have to upgrade in version sequence? 
- If users want to use custom images (either for Contour or Envoy), they probably need to stick with the same versioning?

I think once we have more configurability in the Contour CRD then these questions will be easier to answer, just trying to look ahead such that we understand the bigger picture.

**Comment by danehans** [comment]
Closing since we agreed that the operator version matches Contour's version and they are released in tandem.

xrefs:
- https://projectcontour.io/resources/compatibility-matrix/
- https://projectcontour.io/resources/release-process/
