### ISSUE TITLE
Add linter configuration.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour-operator#9]
**Please describe the problem you have**

Add a golangci-lint configuration to make it easier for contributors to match Go style. This reduces the number of nits that need to be addressed in code review.

**Comment by danehans** [comment]
Currently, golint-ci runs against PRs as a CI job since [this commit](https://github.com/projectcontour/contour-operator/commit/337e206e63f6c8042c634d2024cdaf12e7e68b71). This issue is for adding golint-ci as part of the make `test` target so it can be run locally. golint-ci has different installs for running in CI and running locally.

**Comment by stevesloka** [comment]
We have this already inside: `make check` (https://github.com/projectcontour/contour-operator/blob/main/Makefile#L75)

I think I forgot to tag with the PR (#93).
