### ISSUE TITLE
Restrict Contour by Namespace

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#95]
**Please describe the problem you have**
Currently a `Contour` resource can be created in any namespace desired by a user with cluster credentials. A `Contour` is meant to be a resource exposed to cluster administrators and should be restricted. This issue proposes restricting `Contour` CRUD operations to the same namespace as the operator (i.e. `contour-operator`).

/cc @jpeach @stevesloka @Miciah

**Comment by stevesloka** [comment]
So the idea then is to only have Contour/Envoy pods in the operator namespace? 

Could you restrict where the `Contour` resource is created using RBA?

**Comment by stevesloka** [comment]
Similar issue in regards to which instance of Contour can watch which namespaces: https://github.com/projectcontour/contour/issues/2497

**Comment by jpeach** [comment]
Can you explain the benefit of this in more detail? If an operator can full cluster access then they are a cluster admin, so what's the benefit in restricting where they can create Contour objects? OTOH you could use namespace RBAC to delegate permission to create Contour objects to specific namespaces, which seems like a reasonable thing to want.

**Comment by danehans** [comment]
> So the idea then is to only have Contour/Envoy pods in the operator namespace?
@stevesloka No, contour, envoy, etc.. will be deployed in the ns specified in `contour.spec.namespace.name`. This issue is requesting to restrict what namespaces a `Contour` can be created. Otherwise a `Contour` can be created in any namespace.

**Comment by stevesloka** [comment]
Oh I understand now, you're saying that there's an "admin" Contour namespace where all ContourOperator objects are created, but based upon the namespace/name configured in each object, it will deploy Contour/Envoy to that namespace. 

Is that what we want? To do this you'd have to come up with an "allow list" of where you can deploy these resources vs just creating the ContourOperator object in the target namespace. Maybe you could use label selectors on namespaces or something?

**Comment by danehans** [comment]
> Oh I understand now, you're saying that there's an "admin" Contour namespace where all ContourOperator objects are created, but based upon the namespace/name configured in each object, it will deploy Contour/Envoy to that namespace.

Yes, that is mostly correct. We do not define a `ContourOperator` object. The only object at present is the `Contour` object, which is reconciled by contour-operator and instantiates an instance of Contour (modeled from the [example](https://github.com/projectcontour/contour/tree/main/examples/contour)). The operator runs in [this namespace](https://github.com/projectcontour/contour-operator/blob/main/config/manager/manager.yaml#L6) and we should consider restricting CRUD operations of `Contour` to the same namespace as contour-operator. Even if a user had RBBAC permissions to CRUD a `Contour` in a different namespace, it will be ignored by contour-operator. This approach also has benefits for the operator's reconciliation of `Contour` objects. The operator will only need to watch `Contour` objects in one namespace instead of across all namespaces.

**Comment by Miciah** [comment]
Did we have a discussion as to whether the `Contour` CRD should be namespace-scoped or cluster-scoped?  Are there advantages to its being namespace-scoped if we restrict CRs to a single namespace?  

It might make sense for the `Contour` CRD to be namespace-scoped if we foresee cluster administrators' delegating permission to create `Contour` CRs as James suggests.  Namespace scope would enable such delegation using RBAC, as well as isolation of Contour deployments in a multi-tenant environment.  It would be difficult to delegate and isolate `Contour` CRs otherwise (how do you allow user A to create `Contour` CRs in the `contour-operator` namespace, allow user B to create `Contour` CRs in `contour-operator`, allow users to modify and delete their own CRs, and prohibit user A from modifying or deleting user B's CR or vice versa?).  In this use-case, contour-operator would need to watch `Contour` CRs in all (or at least multiple) namespaces.  

A separate issue is once a user has permission to create a `Contour` CR, how do you control where that user can tell contour-operator (using the CR's `spec.namespace.name` field) to create the Contour and Envoy Deployment and DaemonSet?  I don't think we can handle that using Kubernetes RBAC alone but instead need to defer to something like OPA, Gatekeeper, or custom admission controllers.  (We've been discussing a somewhat similar issue of cross-resource access control with Service APIs:  https://github.com/kubernetes-sigs/service-apis/issues/404).

**Comment by jpeach** [comment]
I think that there's a lack of clarity about what problem is being solved here, which leads to a number of alternatives being proposed with no clear way to choose between them.

I don't see the benefit of the original proposal that ties `Contour` objects to the deployment namespace of the operator, but I could be convinced that there's a need to manage where `Contour` objects can be created and what namespaces they should be allowed to target.

**Comment by stevesloka** [comment]
> Did we have a discussion as to whether the Contour CRD should be namespace-scoped or cluster-scoped? Are there advantages to its being namespace-scoped if we restrict CRs to a single namespace?

I think this a great point @Miciah. In my head, the Contour CRD is namespace scoped and operators deploy them into their own namespaces. The contour-operator namespace only exists to hold the actual operator pods. 

I guess I missed the bit on how the spec.Namespace field was intended to be used.

I think this is worth a conversation to figure out early before we get too far down the road just so we're all on the same page. =)

**Comment by youngnick** [comment]
Catching up on old notifications here, sorry.

It seems like @danehans is talking about having `contour.spec.namespace.name` have the ability to be restricted, so that, regardless of where the `Contour` object is located, users with access to create them can not use that as a way to privilege escalate.

There is another issue - where should the `Contour` objects be created. It seems like most people *expect* the object to be namespace-scoped, and @danehans expects it to be created only in the same namespace as the Operator runs. I'm not clear on whether this reflects the current or desired state of the operator though.

FWIW, I think that the operator should absolutely look in a limited subset of namespaces, probably only one, for `Contour` objects, and there should be a way to restrict what the `contour.spec.namespace.name` field may be set to. This way could be "Use Gatekeeper", similarly to `projectcontour/contour`, or it could be built into the operator. I can see pros and cons either way.

**Comment by danehans** [comment]
>  I'm not clear on whether this reflects the current or desired state of the operator though.

@youngnick the current state is a `Contour` can be created in any namespace. For security purposes, the desired state is to restrict what namespace the operator will process `Contours` from. It's common practice to restrict operands to the ns of the component that manages them, i.e. the operator.

> FWIW, I think that the operator should absolutely look in a limited subset of namespaces, probably only one, for Contour objects, and there should be a way to restrict what the contour.spec.namespace.name field may be set to. 

Keep in mind that only cluster admins should have the RBAC to manage `Contours`, so I don't understand why we should restrict the ns's that they can provision a projectcontour/contour.

**Comment by danehans** [comment]
xref https://github.com/projectcontour/contour-operator/issues/263, Contour objects __will not__ be limited to the operator's namespace. Instead, the operator will reconcile Contour's across all namespaces and use the COntour's meta namespace to provision operands.
